CREATE TABLE EMPLOYEE_CLAIM (
EMPLOYEE_ID NUMBER,
CLAIM_ID NUMBER,
CLAIM_AMT NUMBER,
SUP_STATUS NUMBER,
SUP_DENY VARCHAR2 (250),
DEPT_HEAD_STATUS NUMBER,
DEPT_HEAD_DENY VARCHAR2 (250),
BEN_COORD_STATUS NUMBER,
BEN_COORD_DENY VARCHAR2 (250),
FINAL_CLAIM_STATUS NUMBER,
AWARDED_AMT NUMBER
);

